spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: "jdbc:mysql://localhost:3306/res?serverTimezone=GMT%2B8"
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/res
server:
  port: 80
  servlet:
    context-path: /res
    session:
      timeout: 600000
logging:
  level:
    org.springframework.data.mongodb: debug